### ISSUE TITLE
Select Dropdown ignoring alwaysPreventMouseWheel

### ISSUE THREAD

**Issue by danbopes** [w3co/jcf#23]
Having an issue with a select dropdown ignoring alwaysPreventMouseWheel and wrapNative is false. No matter what I do, I cannot get the dropdown to allow me to scroll the inner content.

Here is a plunkr with the issue: https://plnkr.co/edit/lXSnYS1YlhBJeQCvi77z?p=preview

**Comment by inferpse** [comment]
Hey, @danbopes !

Try to add some CSS styles like following:
```.jcf-list .jcf-list-content {
	vertical-align: top;
	display: inline-block;
	overflow: auto;
	width: 100%;
}```

Some styles are required for correct functionality that's why we have ```css/theme-minimal``` folder in this repo.

And ```alwaysPreventMouseWheel``` option is available only for ```Scrollable``` module, which might be used by the ```Select``` module when it's available. This options is always set to ```true``` in select module - just like native select dropdowns doesn't allow page scroll when scrolling over them.

**Comment by danbopes** [comment]
Yeah, I was trying to add overflow: auto to '.jcf-select-drop-content'.
