### ISSUE TITLE
Max select items

### ISSUE THREAD

**Issue by monymirza** [w3co/jcf#27]
Is there any option to restrict multi select to set max items select ? suppose, i have multi-select list with 10 items and allow to user select only 4.

**Comment by inferpse** [comment]
JCF provides the same behavior as the native ```<select multiple>``` element. And native element doesn't support this. So you need to handle this by yourself:

1. Listen to the ```change``` event on original ```<select>``` element and if more then "max" options are selected then show an alert or change selected options state.
2. Call ```jcf.refresh(selectNode)``` to redraw JCF element based on the current state of original ```<select>```.

**Comment by monymirza** [comment]
"Chosen" plugin support to max select items. is there any possibilty to extend JCF? 
Yes i have handled in custom way.

**Comment by inferpse** [comment]
Well... The idea of JCF is about native form elements customization and their standardized options/methods and events. Because of this JCF could be easily attached or dropped from the project.

That's why we don't have an autocomplete input in selects (like chosen) and custom events. We're trying to reuse native events and elements. But that's a good idea of possibility to extend JCF modules!
But right now this is not supported.

**Comment by monymirza** [comment]
Ok thanks.
