### ISSUE TITLE
Proper way to hide an element

### ISSUE THREAD

**Issue by cfjedimaster** [w3co/jcf#31]
Forgive me for creating an issue to ask for support, but I wasn't sure what the best way to do that was. I've got a client using this library and needs some mods done to it. I thought they were simple - when you change dropdown 1, if the value is so and so, hide or show another drop down. But for the life of me I can't seem to get that working w/ jcf form elements. What's the secret?

**Comment by inferpse** [comment]
Hey, @cfjedimaster !

JCF is designed to support all features of native form elements, and since there's no way to show native select dropdown it's not supported in the library as well. The only way is to enable custom select dropdown. With this option turned on you could make achieve [this behavior](https://jsfiddle.net/52Lyydtf/2/).

**Comment by cfjedimaster** [comment]
Ah - I think I wasn't clear. It looks like hideDropdown, showDropdown opens and closed the drop down. I don't want that. I want to literally hide the *entire* drop down.

**Comment by inferpse** [comment]
Ah... I think I get it know. The easiest way to do it is following:
- Wrap each select inside the `<div>` and toggle container visibility when needed
- Disable JCF and implement requirements with native selects by using `onchange` event
- Enable JCF after everything should work just the same like with native selects
- (Optional step: if your selects are generated after each step then you might want to call `jcf.replaceAll()` after new select appears).

**Comment by cfjedimaster** [comment]
Thank you - got it working!
