### ISSUE TITLE
IE8 select issue

### ISSUE THREAD

**Issue by grun** [w3co/jcf#37]
Is there a way to make it works in IE8?
selectedOption = this.realElement.prop('options')[selectedIndex] doesnt work in IE8 since as i understand it is not an array for IE.

**Comment by inferpse** [comment]
@grun not sure that your issue is related to IE8.
This code should run just fine (here's the simplified example: https://jsfiddle.net/qut6cv5j/ )

Maybe you're updating options dynamically or doing something special with selects?
Please create a fiddle so that it will be possible to reproduce your issue.

**Comment by grun** [comment]
https://gyazo.com/6baa3622f297cc993b32d2a4875c7b51
Have a look

**Comment by inferpse** [comment]
@grun this is fiddler website errors. You should see an alert anyway.
You can create simple HTML page from that fiddler and test locally with IE8. It will work.

**Comment by inferpse** [comment]
Looks like it's not related to the library. Try to use `jcf.refresh()` if your select options are dynamic.
Closing this issue.
