### ISSUE TITLE
Scroll area won't resize until the window is resized

### ISSUE THREAD

**Issue by juliepoignot** [w3co/jcf#48]
Hi, I have an admin type design with a collapsible menu on the left and a scrollable area on the right. However when the menu is closed, the div on the right (.jcf-scrollable) keeps the width it had upon loading the page and only re-takes full width when resizing the window. 

Is there a workaround for this?

**Comment by kyds3k** [comment]
I'm having a similar problem, only with a .jcf-scrollable-wrapper getting set to 0 height until the window is resized.

**Comment by yazonnile** [comment]
That problem exists because you are trying to initialize jcf when scrollable element is hidden or something like that. So jcf element has 0 height as real element.

You can refresh jcf element by yourself in any time you want. For example on window load
`
window.onload = function() {
  jcf.refreshAll();
}
`
For more examples look here please
https://github.com/w3co/jcf#getting-the-instance-of-customized-form-element
https://github.com/w3co/jcf#general-api-information
